#!/usr/bin/env python

def payloads():
    print ""
    print "Plugin Category: Payloads"
    print "===========================================\n"
    print " Name              Version      Description"
    print " ----              -------      -----------"
    print " Doublepulsar      1.3.1        Remotely inject a malicious dll backdoor"
    print " Kodi              1.0.0        Create a malicious addon(backdoor) via kodi.tv"
    print " Bleed             5.0.0        Check for any SSL Vulnerabilities"
    print " Tresspass         3.0.0        A password authenticated PHP web backdoor"
    print " Passby            1.0.0        Setup a usb creds stealer (output: creds.txt)"
    print "\n"

def exploits():
    print ""
    print "Plugin Category: Exploits"
    print "===========================================\n"
    print " Name              Version      Description"
    print " ----              -------      -----------"
    print " Eternalblue       2.2.0        Exploits a vulnerability on SMBv1/SMBv2 protocols"
    print " Internalroute     1.1.0        Exploits multiple vulnerabilities in routers"
    print " Aurora            4.0.1        Internet Explorer 6 url vulnerability"
    print " Smartremote       2.0.0        Take over a smart tv's remote control"
    print " Blueborne         1.0.0        Android Bluetooth memory leak all devices even cars"
    print " Byepot            1.0.0        Bypass Paid Hotspots using an old trick"
    print "\n"

def others():
    print ""
    print "Plugin Category: Others"
    print "===========================================\n"
    print " Name              Version      Description"
    print " ----              -------      -----------"
    print " Scan              1.0.2        Information gathering tool"
    print " jailpwn           3.1.0        Jailbroken default ssh password tool"
    print " Handler           1.0.0        Create a listener"
    print " Poppy             1.1.0        Arp spoof && sniff unencrypted passwords on all protocals"
    print " Redcarpet         2.1.5        Encrypt a user directory"
    print " Picklock          1.2.2        Picklock Mulitple devices Pincodes"
    print " Dnsspoof          1.0.0        DNS Spoof all http requests"
    print " Credswipe         1.0.0        A Credit Card swiper"
    print " Rfpwn             4.1.0        Rfcat suitable device to bruteforce a special AM OOK or raw binary signal"
    print " Ftpbrute          1.2.2        Brute-force attack an ftp(file transfer protocol) server"
    print " Wifijammer        1.0.0        Deauth wifi networks around your area"
    print "\n"

def utilities():
    print ""
    print "Plugin Category: Utilities"
    print "===========================================\n"
    print " Name              Version      Description"
    print " ----              -------      -----------"
    print " Smbtouch          2.3.3        check if the target is vulnerable to samba exploits"
    print " Architouch        1.0.0        check if the target is x64 or x86"
    print "\n"

def all():
    print ""
    print "Plugin Category: All"
    print "===========================================\n"
    print " Name              Version      Description"
    print " ----              -------      -----------"
    print " Scan              1.0.2        Information gathering tool"
    print " jailpwn           3.1.0        Jailbroken default ssh password tool"
    print " Eternalblue       2.2.0        Exploits a vulnerability on SMBv1/SMBv2 protocols"
    print " Internalroute     1.1.0        Exploits multiple vulnerabilities in routers"
    print " Aurora            4.0.1        Internet Explorer 6 url vulnerability"
    print " Doublepulsar      1.3.1        Remotely inject a malicious dll backdoor"
    print " Kodi              1.0.0        Create a malicious addon(backdoor) via kodi.tv"
    print " Bleed             5.0.0        Check for any SSL Vulnerabilities"
    print " Tresspass         3.0.0        A password authenticated PHP web backdoor"
    print " Handler           1.0.0        Create a listener"
    print " Poppy             1.1.0        Arp spoof && sniff unencrypted passwords on all protocals"
    print " Redcarpet         2.1.5        Encrypt a user directory"
    print " Picklock          1.2.2        Picklock Mulitple devices Pincodes"
    print " Passby            1.0.0        Setup a usb creds stealer (output: creds.txt)"
    print " Dnsspoof          1.0.0        DNS Spoof all http requests"
    print " Smartremote       2.0.0        Take over a smart tv's remote control"
    print " Blueborne         1.0.0        Bluetooth memory leak all devices even cars"
    print " Credswipe         1.0.0        A Credit Card swiper"
    print " Rfpwn             4.1.0        Rfcat suitable device to bruteforce a special AM OOK or raw binary signal"
    print " Ftpbrute          1.2.2        Brute-force attack an ftp(file transfer protocol) server"
    print " Wifijammer        1.0.0        Deauth wifi networks around your area"
    print " Smbtouch          2.3.3        check if the target is vulnerable to samba exploits"
    print " Architouch        1.0.0        check if the target is x64 or x86"
    print " Byepot            1.0.0        Bypass Paid Hotspots using an old trick"
    print "\n"
